# Snakefile
import os, re, glob, fnmatch
import pandas as pd

configfile: 'config/config.yml'

# Decode original IDs into new IDs
recoding_keys = pd.read_csv(config['bids_decoder'])

subjects = recoding_keys['bids'] #['P01','P03','P04','P05']
subjects  = [ '{:03d}'.format(i) for i in recoding_keys['bids'] ]

recoding_iterator = zip(subjects,recoding_keys['dicom'])
recoding_dict = dict(recoding_iterator)

# Expected output
rule all:
    input:
        # expand('tar/sub-{subject}/sub-{subject}_tar.files', subject=subjects),
        expand('bids/sub-{subject}/tar2bids.done', subject=subjects)

# BIDSify data
include: 'rules/bids.smk'

# Other rules, e.g., MP2RAGE processing
