bids_decoder: resources/bids_decoder.csv

data:
    raw: /DATA_CEMEREM/data/protocols/magnetom/brain
    tar: /home/rhaast/01_PROJECTS/epilepsy/tar

include:
    - '*b1map*'
    - '*mp2rage*'
    - '*flaws*'
    - '*qsm*separated*'
    - '*space*'
    - '*ep2d*'
    - '*dti*2shells'
    - '*23na*'
    - '*modified-spokes'

tar2bids: /home/rhaast/00_SOFTWARE/tar2bids/tar2bids
heuristics: /home/rhaast/00_SOFTWARE/tar2bids/heuristics/cemerem_base.py

containers:
    dicom2tar: /home/rhaast/00_SOFTWARE/containers/khanlab_dicom2tar_v0.0.5.sif
    tar2bids: /home/rhaast/00_SOFTWARE/containers/khanlab_tar2bids_latest.sif
